export const USER_API_END_POINT= "http://localhost:8000/api"
export const GET_ALL_JOBS_END_POINT= "http://localhost:8000/api/jobs/getAllJobs"
export const JOB_DES_END_POINT= "http://localhost:8000/api/jobs/getJobById"
export const APPLY_JOB_END_POINT= "http://localhost:8000/api/application/apply"
export const REGISTER_COMPANY_END_POINT= "http://localhost:8000/api/company/create"
export const GET_ALL_COMPANIES_END_POINT= "http://localhost:8000/api/company/getAllCompanies"
export const GET_COMPANY_BY_ID_END_POINT= "http://localhost:8000/api/company/getCompanyById"
export const UPDATE_COMPANY_DETAILS_END_POINT= "http://localhost:8000/api/company/update/company/details"

export const GET_ADMIN_JOBS_END_POINT= "http://localhost:8000/api/jobs/getAdminJobs"
export const CREATE_JOB_END_POINT= "http://localhost:8000/api/jobs/postJob"
export const POST_JOB_END_POINT= "http://localhost:8000/api/jobs/postJob"
export const JOB_BY_ID_END_POINT= "http://localhost:8000/api/jobs/getJobById"
export const JOB_UPDATE_END_POINT= "http://localhost:8000/api/jobs/update"
export const GET_APPLICANTS_END_POINT= "http://localhost:8000/api/application/get/applicant"
export const UPDATE_STATUS_END_POINT= "http://localhost:8000/api/application/update/status"
export const GET_APPLIED_JOBS_END_POINT= "http://localhost:8000/api/application/applied/jobs"